name: BuildAndTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    - uses: actions/checkout@v1
 
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: 039c43988dcb9e1143816b374bfd0ce30831b061
      shell: powershell
      working-directory: ./src
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"sai" /o:"saibhargav" /d:sonar.login="039c43988dcb9e1143816b374bfd0ce30831b061" /d:sonar.host.url="https://sonarcloud.io"
        working-directory: ./src
        dotnet build --configuration Release
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="039c43988dcb9e1143816b374bfd0ce30831b061"
    - name: Run Tests
      working-directory: ./src
      run: dotnet test
